name: Publish

on:
  schedule:
    - cron: '15,55 * * * *'  # twice every hour.

jobs:
  publish-data:
    runs-on: macOS-latest
    env:
      ELEPHANT_SQL_DBNAME: ${{ secrets.ELEPHANT_SQL_DBNAME }}
      ELEPHANT_SQL_HOST: ${{ secrets.ELEPHANT_SQL_HOST }}
      ELEPHANT_SQL_USER: ${{ secrets.ELEPHANT_SQL_USER }}
      ELEPHANT_SQL_PASSWORD: ${{ secrets.ELEPHANT_SQL_PASSWORD }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install formattable package
        run: Rscript -e 'install.packages("formattable", dependencies = TRUE)'
      - name: Install htmltools package
        run: Rscript -e 'install.packages("htmltools", dependencies = TRUE)'
      - name: Install webshot package
        run: Rscript -e 'install.packages("webshot", dependencies = TRUE)'
      - name: Install phantomjs() package
        run: Rscript -e 'webshot::install_phantomjs()'
      - name: Create and post tweet
        run: Rscript publish_ligaprimer.R
